// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cn/edu/whu/infrastructure/query/coprocessor/proto/TopologicalQuery.proto

package query.coprocessor.proto;

import org.locationtech.jts.io.ParseException;

public final class TopologicalQueryCondition {
  private TopologicalQueryCondition() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QueryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    java.util.List<query.coprocessor.proto.TopologicalQueryCondition.Range>
        getRangesList();
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    query.coprocessor.proto.TopologicalQueryCondition.Range getRanges(int index);
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    int getRangesCount();
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    java.util.List<? extends query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder>
        getRangesOrBuilderList();
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder getRangesOrBuilder(
        int index);

    /**
     * <code>required bytes queryObjWKB = 2;</code>
     */
    boolean hasQueryObjWKB();
    /**
     * <code>required bytes queryObjWKB = 2;</code>
     */
    com.google.protobuf.ByteString getQueryObjWKB();

    /**
     * <code>required bool isContain = 3;</code>
     */
    boolean hasIsContain();
    /**
     * <code>required bool isContain = 3;</code>
     */
    boolean getIsContain();

    /**
     * <code>required bool isRefine = 4;</code>
     */
    boolean hasIsRefine();
    /**
     * <code>required bool isRefine = 4;</code>
     */
    boolean getIsRefine();
  }
  /**
   * Protobuf type {@code QueryRequest}
   */
  public static final class QueryRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QueryRequest)
      QueryRequestOrBuilder {
    // Use QueryRequest.newBuilder() to construct.
    private QueryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueryRequest defaultInstance;
    public static QueryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public QueryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ranges_ = new java.util.ArrayList<query.coprocessor.proto.TopologicalQueryCondition.Range>();
                mutable_bitField0_ |= 0x00000001;
              }
              ranges_.add(input.readMessage(query.coprocessor.proto.TopologicalQueryCondition.Range.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              queryObjWKB_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              isContain_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              isRefine_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ranges_ = java.util.Collections.unmodifiableList(ranges_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.class, query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<QueryRequest> PARSER =
        new com.google.protobuf.AbstractParser<QueryRequest>() {
      public QueryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QueryRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RANGES_FIELD_NUMBER = 1;
    private java.util.List<query.coprocessor.proto.TopologicalQueryCondition.Range> ranges_;
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public java.util.List<query.coprocessor.proto.TopologicalQueryCondition.Range> getRangesList() {
      return ranges_;
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public java.util.List<? extends query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder>
        getRangesOrBuilderList() {
      return ranges_;
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public int getRangesCount() {
      return ranges_.size();
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public query.coprocessor.proto.TopologicalQueryCondition.Range getRanges(int index) {
      return ranges_.get(index);
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder getRangesOrBuilder(
        int index) {
      return ranges_.get(index);
    }

    public static final int QUERYOBJWKB_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString queryObjWKB_;
    /**
     * <code>required bytes queryObjWKB = 2;</code>
     */
    public boolean hasQueryObjWKB() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes queryObjWKB = 2;</code>
     */
    public com.google.protobuf.ByteString getQueryObjWKB() {
      return queryObjWKB_;
    }

    public static final int ISCONTAIN_FIELD_NUMBER = 3;
    private boolean isContain_;
    /**
     * <code>required bool isContain = 3;</code>
     */
    public boolean hasIsContain() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isContain = 3;</code>
     */
    public boolean getIsContain() {
      return isContain_;
    }

    public static final int ISREFINE_FIELD_NUMBER = 4;
    private boolean isRefine_;
    /**
     * <code>required bool isRefine = 4;</code>
     */
    public boolean hasIsRefine() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool isRefine = 4;</code>
     */
    public boolean getIsRefine() {
      return isRefine_;
    }

    private void initFields() {
      ranges_ = java.util.Collections.emptyList();
      queryObjWKB_ = com.google.protobuf.ByteString.EMPTY;
      isContain_ = false;
      isRefine_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQueryObjWKB()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsContain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsRefine()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRangesCount(); i++) {
        if (!getRanges(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ranges_.size(); i++) {
        output.writeMessage(1, ranges_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, queryObjWKB_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(3, isContain_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(4, isRefine_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < ranges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ranges_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, queryObjWKB_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isContain_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isRefine_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof query.coprocessor.proto.TopologicalQueryCondition.QueryRequest)) {
        return super.equals(obj);
      }
      query.coprocessor.proto.TopologicalQueryCondition.QueryRequest other = (query.coprocessor.proto.TopologicalQueryCondition.QueryRequest) obj;

      boolean result = true;
      result = result && getRangesList()
          .equals(other.getRangesList());
      result = result && (hasQueryObjWKB() == other.hasQueryObjWKB());
      if (hasQueryObjWKB()) {
        result = result && getQueryObjWKB()
            .equals(other.getQueryObjWKB());
      }
      result = result && (hasIsContain() == other.hasIsContain());
      if (hasIsContain()) {
        result = result && (getIsContain()
            == other.getIsContain());
      }
      result = result && (hasIsRefine() == other.hasIsRefine());
      if (hasIsRefine()) {
        result = result && (getIsRefine()
            == other.getIsRefine());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getRangesCount() > 0) {
        hash = (37 * hash) + RANGES_FIELD_NUMBER;
        hash = (53 * hash) + getRangesList().hashCode();
      }
      if (hasQueryObjWKB()) {
        hash = (37 * hash) + QUERYOBJWKB_FIELD_NUMBER;
        hash = (53 * hash) + getQueryObjWKB().hashCode();
      }
      if (hasIsContain()) {
        hash = (37 * hash) + ISCONTAIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsContain());
      }
      if (hasIsRefine()) {
        hash = (37 * hash) + ISREFINE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsRefine());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(query.coprocessor.proto.TopologicalQueryCondition.QueryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryRequest)
        query.coprocessor.proto.TopologicalQueryCondition.QueryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.class, query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.Builder.class);
      }

      // Construct using query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRangesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rangesBuilder_ == null) {
          ranges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rangesBuilder_.clear();
        }
        queryObjWKB_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        isContain_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        isRefine_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryRequest_descriptor;
      }

      public query.coprocessor.proto.TopologicalQueryCondition.QueryRequest getDefaultInstanceForType() {
        return query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.getDefaultInstance();
      }

      public query.coprocessor.proto.TopologicalQueryCondition.QueryRequest build() {
        query.coprocessor.proto.TopologicalQueryCondition.QueryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public query.coprocessor.proto.TopologicalQueryCondition.QueryRequest buildPartial() {
        query.coprocessor.proto.TopologicalQueryCondition.QueryRequest result = new query.coprocessor.proto.TopologicalQueryCondition.QueryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rangesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            ranges_ = java.util.Collections.unmodifiableList(ranges_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ranges_ = ranges_;
        } else {
          result.ranges_ = rangesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.queryObjWKB_ = queryObjWKB_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isContain_ = isContain_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isRefine_ = isRefine_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof query.coprocessor.proto.TopologicalQueryCondition.QueryRequest) {
          return mergeFrom((query.coprocessor.proto.TopologicalQueryCondition.QueryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(query.coprocessor.proto.TopologicalQueryCondition.QueryRequest other) {
        if (other == query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.getDefaultInstance()) return this;
        if (rangesBuilder_ == null) {
          if (!other.ranges_.isEmpty()) {
            if (ranges_.isEmpty()) {
              ranges_ = other.ranges_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRangesIsMutable();
              ranges_.addAll(other.ranges_);
            }
            onChanged();
          }
        } else {
          if (!other.ranges_.isEmpty()) {
            if (rangesBuilder_.isEmpty()) {
              rangesBuilder_.dispose();
              rangesBuilder_ = null;
              ranges_ = other.ranges_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rangesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRangesFieldBuilder() : null;
            } else {
              rangesBuilder_.addAllMessages(other.ranges_);
            }
          }
        }
        if (other.hasQueryObjWKB()) {
          setQueryObjWKB(other.getQueryObjWKB());
        }
        if (other.hasIsContain()) {
          setIsContain(other.getIsContain());
        }
        if (other.hasIsRefine()) {
          setIsRefine(other.getIsRefine());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQueryObjWKB()) {
          
          return false;
        }
        if (!hasIsContain()) {
          
          return false;
        }
        if (!hasIsRefine()) {
          
          return false;
        }
        for (int i = 0; i < getRangesCount(); i++) {
          if (!getRanges(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        query.coprocessor.proto.TopologicalQueryCondition.QueryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (query.coprocessor.proto.TopologicalQueryCondition.QueryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<query.coprocessor.proto.TopologicalQueryCondition.Range> ranges_ =
        java.util.Collections.emptyList();
      private void ensureRangesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ranges_ = new java.util.ArrayList<query.coprocessor.proto.TopologicalQueryCondition.Range>(ranges_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          query.coprocessor.proto.TopologicalQueryCondition.Range, query.coprocessor.proto.TopologicalQueryCondition.Range.Builder, query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder> rangesBuilder_;

      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public java.util.List<query.coprocessor.proto.TopologicalQueryCondition.Range> getRangesList() {
        if (rangesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ranges_);
        } else {
          return rangesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public int getRangesCount() {
        if (rangesBuilder_ == null) {
          return ranges_.size();
        } else {
          return rangesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public query.coprocessor.proto.TopologicalQueryCondition.Range getRanges(int index) {
        if (rangesBuilder_ == null) {
          return ranges_.get(index);
        } else {
          return rangesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder setRanges(
          int index, query.coprocessor.proto.TopologicalQueryCondition.Range value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.set(index, value);
          onChanged();
        } else {
          rangesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder setRanges(
          int index, query.coprocessor.proto.TopologicalQueryCondition.Range.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.set(index, builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(query.coprocessor.proto.TopologicalQueryCondition.Range value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.add(value);
          onChanged();
        } else {
          rangesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(
          int index, query.coprocessor.proto.TopologicalQueryCondition.Range value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.add(index, value);
          onChanged();
        } else {
          rangesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(
          query.coprocessor.proto.TopologicalQueryCondition.Range.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.add(builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(
          int index, query.coprocessor.proto.TopologicalQueryCondition.Range.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.add(index, builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addAllRanges(
          java.lang.Iterable<? extends query.coprocessor.proto.TopologicalQueryCondition.Range> values) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ranges_);
          onChanged();
        } else {
          rangesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder clearRanges() {
        if (rangesBuilder_ == null) {
          ranges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rangesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder removeRanges(int index) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.remove(index);
          onChanged();
        } else {
          rangesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public query.coprocessor.proto.TopologicalQueryCondition.Range.Builder getRangesBuilder(
          int index) {
        return getRangesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder getRangesOrBuilder(
          int index) {
        if (rangesBuilder_ == null) {
          return ranges_.get(index);  } else {
          return rangesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public java.util.List<? extends query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder>
           getRangesOrBuilderList() {
        if (rangesBuilder_ != null) {
          return rangesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ranges_);
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public query.coprocessor.proto.TopologicalQueryCondition.Range.Builder addRangesBuilder() {
        return getRangesFieldBuilder().addBuilder(
            query.coprocessor.proto.TopologicalQueryCondition.Range.getDefaultInstance());
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public query.coprocessor.proto.TopologicalQueryCondition.Range.Builder addRangesBuilder(
          int index) {
        return getRangesFieldBuilder().addBuilder(
            index, query.coprocessor.proto.TopologicalQueryCondition.Range.getDefaultInstance());
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public java.util.List<query.coprocessor.proto.TopologicalQueryCondition.Range.Builder>
           getRangesBuilderList() {
        return getRangesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          query.coprocessor.proto.TopologicalQueryCondition.Range, query.coprocessor.proto.TopologicalQueryCondition.Range.Builder, query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder>
          getRangesFieldBuilder() {
        if (rangesBuilder_ == null) {
          rangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              query.coprocessor.proto.TopologicalQueryCondition.Range, query.coprocessor.proto.TopologicalQueryCondition.Range.Builder, query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder>(
                  ranges_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          ranges_ = null;
        }
        return rangesBuilder_;
      }

      private com.google.protobuf.ByteString queryObjWKB_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes queryObjWKB = 2;</code>
       */
      public boolean hasQueryObjWKB() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes queryObjWKB = 2;</code>
       */
      public com.google.protobuf.ByteString getQueryObjWKB() {
        return queryObjWKB_;
      }
      /**
       * <code>required bytes queryObjWKB = 2;</code>
       */
      public Builder setQueryObjWKB(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        queryObjWKB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes queryObjWKB = 2;</code>
       */
      public Builder clearQueryObjWKB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        queryObjWKB_ = getDefaultInstance().getQueryObjWKB();
        onChanged();
        return this;
      }

      private boolean isContain_ ;
      /**
       * <code>required bool isContain = 3;</code>
       */
      public boolean hasIsContain() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool isContain = 3;</code>
       */
      public boolean getIsContain() {
        return isContain_;
      }
      /**
       * <code>required bool isContain = 3;</code>
       */
      public Builder setIsContain(boolean value) {
        bitField0_ |= 0x00000004;
        isContain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isContain = 3;</code>
       */
      public Builder clearIsContain() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isContain_ = false;
        onChanged();
        return this;
      }

      private boolean isRefine_ ;
      /**
       * <code>required bool isRefine = 4;</code>
       */
      public boolean hasIsRefine() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool isRefine = 4;</code>
       */
      public boolean getIsRefine() {
        return isRefine_;
      }
      /**
       * <code>required bool isRefine = 4;</code>
       */
      public Builder setIsRefine(boolean value) {
        bitField0_ |= 0x00000008;
        isRefine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isRefine = 4;</code>
       */
      public Builder clearIsRefine() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isRefine_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QueryRequest)
    }

    static {
      defaultInstance = new QueryRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QueryRequest)
  }

  public interface QueryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes results = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getResultsList();
    /**
     * <code>repeated bytes results = 1;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated bytes results = 1;</code>
     */
    com.google.protobuf.ByteString getResults(int index);
  }
  /**
   * Protobuf type {@code QueryResponse}
   */
  public static final class QueryResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:QueryResponse)
      QueryResponseOrBuilder {
    // Use QueryResponse.newBuilder() to construct.
    private QueryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueryResponse defaultInstance;
    public static QueryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public QueryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                results_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              results_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.class, query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<QueryResponse> PARSER =
        new com.google.protobuf.AbstractParser<QueryResponse>() {
      public QueryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QueryResponse> getParserForType() {
      return PARSER;
    }

    public static final int RESULTS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> results_;
    /**
     * <code>repeated bytes results = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getResultsList() {
      return results_;
    }
    /**
     * <code>repeated bytes results = 1;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated bytes results = 1;</code>
     */
    public com.google.protobuf.ByteString getResults(int index) {
      return results_.get(index);
    }

    private void initFields() {
      results_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < results_.size(); i++) {
        output.writeBytes(1, results_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < results_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(results_.get(i));
        }
        size += dataSize;
        size += 1 * getResultsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof query.coprocessor.proto.TopologicalQueryCondition.QueryResponse)) {
        return super.equals(obj);
      }
      query.coprocessor.proto.TopologicalQueryCondition.QueryResponse other = (query.coprocessor.proto.TopologicalQueryCondition.QueryResponse) obj;

      boolean result = true;
      result = result && getResultsList()
          .equals(other.getResultsList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(query.coprocessor.proto.TopologicalQueryCondition.QueryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryResponse)
        query.coprocessor.proto.TopologicalQueryCondition.QueryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.class, query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.Builder.class);
      }

      // Construct using query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_QueryResponse_descriptor;
      }

      public query.coprocessor.proto.TopologicalQueryCondition.QueryResponse getDefaultInstanceForType() {
        return query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.getDefaultInstance();
      }

      public query.coprocessor.proto.TopologicalQueryCondition.QueryResponse build() {
        query.coprocessor.proto.TopologicalQueryCondition.QueryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public query.coprocessor.proto.TopologicalQueryCondition.QueryResponse buildPartial() {
        query.coprocessor.proto.TopologicalQueryCondition.QueryResponse result = new query.coprocessor.proto.TopologicalQueryCondition.QueryResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.results_ = results_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof query.coprocessor.proto.TopologicalQueryCondition.QueryResponse) {
          return mergeFrom((query.coprocessor.proto.TopologicalQueryCondition.QueryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(query.coprocessor.proto.TopologicalQueryCondition.QueryResponse other) {
        if (other == query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.getDefaultInstance()) return this;
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        query.coprocessor.proto.TopologicalQueryCondition.QueryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (query.coprocessor.proto.TopologicalQueryCondition.QueryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> results_ = java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          results_ = new java.util.ArrayList<com.google.protobuf.ByteString>(results_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes results = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getResultsList() {
        return java.util.Collections.unmodifiableList(results_);
      }
      /**
       * <code>repeated bytes results = 1;</code>
       */
      public int getResultsCount() {
        return results_.size();
      }
      /**
       * <code>repeated bytes results = 1;</code>
       */
      public com.google.protobuf.ByteString getResults(int index) {
        return results_.get(index);
      }
      /**
       * <code>repeated bytes results = 1;</code>
       */
      public Builder setResults(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes results = 1;</code>
       */
      public Builder addResults(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResultsIsMutable();
        results_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes results = 1;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes results = 1;</code>
       */
      public Builder clearResults() {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QueryResponse)
    }

    static {
      defaultInstance = new QueryResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QueryResponse)
  }

  public interface RangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Range)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes rangeStart = 1;</code>
     */
    boolean hasRangeStart();
    /**
     * <code>required bytes rangeStart = 1;</code>
     */
    com.google.protobuf.ByteString getRangeStart();

    /**
     * <code>required bytes rangeEnd = 2;</code>
     */
    boolean hasRangeEnd();
    /**
     * <code>required bytes rangeEnd = 2;</code>
     */
    com.google.protobuf.ByteString getRangeEnd();

    /**
     * <code>required bool isContained = 3;</code>
     */
    boolean hasIsContained();
    /**
     * <code>required bool isContained = 3;</code>
     */
    boolean getIsContained();
  }
  /**
   * Protobuf type {@code Range}
   */
  public static final class Range extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Range)
      RangeOrBuilder {
    // Use Range.newBuilder() to construct.
    private Range(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Range(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Range defaultInstance;
    public static Range getDefaultInstance() {
      return defaultInstance;
    }

    public Range getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Range(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rangeStart_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rangeEnd_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isContained_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return query.coprocessor.proto.TopologicalQueryCondition.internal_static_Range_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return query.coprocessor.proto.TopologicalQueryCondition.internal_static_Range_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              query.coprocessor.proto.TopologicalQueryCondition.Range.class, query.coprocessor.proto.TopologicalQueryCondition.Range.Builder.class);
    }

    public static com.google.protobuf.Parser<Range> PARSER =
        new com.google.protobuf.AbstractParser<Range>() {
      public Range parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Range(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Range> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RANGESTART_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rangeStart_;
    /**
     * <code>required bytes rangeStart = 1;</code>
     */
    public boolean hasRangeStart() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes rangeStart = 1;</code>
     */
    public com.google.protobuf.ByteString getRangeStart() {
      return rangeStart_;
    }

    public static final int RANGEEND_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rangeEnd_;
    /**
     * <code>required bytes rangeEnd = 2;</code>
     */
    public boolean hasRangeEnd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes rangeEnd = 2;</code>
     */
    public com.google.protobuf.ByteString getRangeEnd() {
      return rangeEnd_;
    }

    public static final int ISCONTAINED_FIELD_NUMBER = 3;
    private boolean isContained_;
    /**
     * <code>required bool isContained = 3;</code>
     */
    public boolean hasIsContained() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool isContained = 3;</code>
     */
    public boolean getIsContained() {
      return isContained_;
    }

    private void initFields() {
      rangeStart_ = com.google.protobuf.ByteString.EMPTY;
      rangeEnd_ = com.google.protobuf.ByteString.EMPTY;
      isContained_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRangeStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRangeEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsContained()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, rangeStart_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, rangeEnd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isContained_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rangeStart_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rangeEnd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isContained_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof query.coprocessor.proto.TopologicalQueryCondition.Range)) {
        return super.equals(obj);
      }
      query.coprocessor.proto.TopologicalQueryCondition.Range other = (query.coprocessor.proto.TopologicalQueryCondition.Range) obj;

      boolean result = true;
      result = result && (hasRangeStart() == other.hasRangeStart());
      if (hasRangeStart()) {
        result = result && getRangeStart()
            .equals(other.getRangeStart());
      }
      result = result && (hasRangeEnd() == other.hasRangeEnd());
      if (hasRangeEnd()) {
        result = result && getRangeEnd()
            .equals(other.getRangeEnd());
      }
      result = result && (hasIsContained() == other.hasIsContained());
      if (hasIsContained()) {
        result = result && (getIsContained()
            == other.getIsContained());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRangeStart()) {
        hash = (37 * hash) + RANGESTART_FIELD_NUMBER;
        hash = (53 * hash) + getRangeStart().hashCode();
      }
      if (hasRangeEnd()) {
        hash = (37 * hash) + RANGEEND_FIELD_NUMBER;
        hash = (53 * hash) + getRangeEnd().hashCode();
      }
      if (hasIsContained()) {
        hash = (37 * hash) + ISCONTAINED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsContained());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static query.coprocessor.proto.TopologicalQueryCondition.Range parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(query.coprocessor.proto.TopologicalQueryCondition.Range prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Range}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Range)
        query.coprocessor.proto.TopologicalQueryCondition.RangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_Range_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_Range_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                query.coprocessor.proto.TopologicalQueryCondition.Range.class, query.coprocessor.proto.TopologicalQueryCondition.Range.Builder.class);
      }

      // Construct using query.coprocessor.proto.TopologicalQueryCondition.Range.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rangeStart_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        rangeEnd_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        isContained_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return query.coprocessor.proto.TopologicalQueryCondition.internal_static_Range_descriptor;
      }

      public query.coprocessor.proto.TopologicalQueryCondition.Range getDefaultInstanceForType() {
        return query.coprocessor.proto.TopologicalQueryCondition.Range.getDefaultInstance();
      }

      public query.coprocessor.proto.TopologicalQueryCondition.Range build() {
        query.coprocessor.proto.TopologicalQueryCondition.Range result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public query.coprocessor.proto.TopologicalQueryCondition.Range buildPartial() {
        query.coprocessor.proto.TopologicalQueryCondition.Range result = new query.coprocessor.proto.TopologicalQueryCondition.Range(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rangeStart_ = rangeStart_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rangeEnd_ = rangeEnd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isContained_ = isContained_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof query.coprocessor.proto.TopologicalQueryCondition.Range) {
          return mergeFrom((query.coprocessor.proto.TopologicalQueryCondition.Range)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(query.coprocessor.proto.TopologicalQueryCondition.Range other) {
        if (other == query.coprocessor.proto.TopologicalQueryCondition.Range.getDefaultInstance()) return this;
        if (other.hasRangeStart()) {
          setRangeStart(other.getRangeStart());
        }
        if (other.hasRangeEnd()) {
          setRangeEnd(other.getRangeEnd());
        }
        if (other.hasIsContained()) {
          setIsContained(other.getIsContained());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRangeStart()) {
          
          return false;
        }
        if (!hasRangeEnd()) {
          
          return false;
        }
        if (!hasIsContained()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        query.coprocessor.proto.TopologicalQueryCondition.Range parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (query.coprocessor.proto.TopologicalQueryCondition.Range) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString rangeStart_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes rangeStart = 1;</code>
       */
      public boolean hasRangeStart() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes rangeStart = 1;</code>
       */
      public com.google.protobuf.ByteString getRangeStart() {
        return rangeStart_;
      }
      /**
       * <code>required bytes rangeStart = 1;</code>
       */
      public Builder setRangeStart(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rangeStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes rangeStart = 1;</code>
       */
      public Builder clearRangeStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rangeStart_ = getDefaultInstance().getRangeStart();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rangeEnd_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes rangeEnd = 2;</code>
       */
      public boolean hasRangeEnd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes rangeEnd = 2;</code>
       */
      public com.google.protobuf.ByteString getRangeEnd() {
        return rangeEnd_;
      }
      /**
       * <code>required bytes rangeEnd = 2;</code>
       */
      public Builder setRangeEnd(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rangeEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes rangeEnd = 2;</code>
       */
      public Builder clearRangeEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rangeEnd_ = getDefaultInstance().getRangeEnd();
        onChanged();
        return this;
      }

      private boolean isContained_ ;
      /**
       * <code>required bool isContained = 3;</code>
       */
      public boolean hasIsContained() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool isContained = 3;</code>
       */
      public boolean getIsContained() {
        return isContained_;
      }
      /**
       * <code>required bool isContained = 3;</code>
       */
      public Builder setIsContained(boolean value) {
        bitField0_ |= 0x00000004;
        isContained_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isContained = 3;</code>
       */
      public Builder clearIsContained() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isContained_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Range)
    }

    static {
      defaultInstance = new Range(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Range)
  }

  /**
   * Protobuf service {@code QueryService}
   */
  public static abstract class QueryService
      implements com.google.protobuf.Service {
    protected QueryService() {}

    public interface Interface {
      /**
       * <code>rpc query(.QueryRequest) returns (.QueryResponse);</code>
       */
      public abstract void query(
          com.google.protobuf.RpcController controller,
          query.coprocessor.proto.TopologicalQueryCondition.QueryRequest request,
          com.google.protobuf.RpcCallback<query.coprocessor.proto.TopologicalQueryCondition.QueryResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new QueryService() {
        @java.lang.Override
        public  void query(
            com.google.protobuf.RpcController controller,
            query.coprocessor.proto.TopologicalQueryCondition.QueryRequest request,
            com.google.protobuf.RpcCallback<query.coprocessor.proto.TopologicalQueryCondition.QueryResponse> done) {
          impl.query(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.query(controller, (query.coprocessor.proto.TopologicalQueryCondition.QueryRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc query(.QueryRequest) returns (.QueryResponse);</code>
     */
    public abstract void query(
        com.google.protobuf.RpcController controller,
        query.coprocessor.proto.TopologicalQueryCondition.QueryRequest request,
        com.google.protobuf.RpcCallback<query.coprocessor.proto.TopologicalQueryCondition.QueryResponse> done) throws ParseException;

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return query.coprocessor.proto.TopologicalQueryCondition.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          try {
            this.query(controller, (QueryRequest)request,
              com.google.protobuf.RpcUtil.<QueryResponse>specializeCallback(
                done));
          } catch (ParseException e) {
            e.printStackTrace();
          }
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return query.coprocessor.proto.TopologicalQueryCondition.QueryRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends query.coprocessor.proto.TopologicalQueryCondition.QueryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void query(
          com.google.protobuf.RpcController controller,
          query.coprocessor.proto.TopologicalQueryCondition.QueryRequest request,
          com.google.protobuf.RpcCallback<query.coprocessor.proto.TopologicalQueryCondition.QueryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.class,
            query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public query.coprocessor.proto.TopologicalQueryCondition.QueryResponse query(
          com.google.protobuf.RpcController controller,
          query.coprocessor.proto.TopologicalQueryCondition.QueryRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public query.coprocessor.proto.TopologicalQueryCondition.QueryResponse query(
          com.google.protobuf.RpcController controller,
          query.coprocessor.proto.TopologicalQueryCondition.QueryRequest request)
          throws com.google.protobuf.ServiceException {
        return (query.coprocessor.proto.TopologicalQueryCondition.QueryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          query.coprocessor.proto.TopologicalQueryCondition.QueryResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:QueryService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Range_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Range_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nHcn/edu/whu/infrastructure/query/coproc" +
      "essor/proto/TopologicalQuery.proto\"`\n\014Qu" +
      "eryRequest\022\026\n\006ranges\030\001 \003(\0132\006.Range\022\023\n\013qu" +
      "eryObjWKB\030\002 \002(\014\022\021\n\tisContain\030\003 \002(\010\022\020\n\010is" +
      "Refine\030\004 \002(\010\" \n\rQueryResponse\022\017\n\007results" +
      "\030\001 \003(\014\"B\n\005Range\022\022\n\nrangeStart\030\001 \002(\014\022\020\n\010r" +
      "angeEnd\030\002 \002(\014\022\023\n\013isContained\030\003 \002(\01026\n\014Qu" +
      "eryService\022&\n\005query\022\r.QueryRequest\032\016.Que" +
      "ryResponseBV\n1cn.edu.whu.infrastructure." +
      "query.coprocessor.protoB\031TopologicalQuer",
      "yConditionH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueryRequest_descriptor,
        new java.lang.String[] { "Ranges", "QueryObjWKB", "IsContain", "IsRefine", });
    internal_static_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_QueryResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_Range_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Range_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Range_descriptor,
        new java.lang.String[] { "RangeStart", "RangeEnd", "IsContained", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
