// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AreaQueryCondition.proto

package query.coprocessor.protobuf;

import static com.google.protobuf.Internal.hashLong;

public final class AreaQueryCondition {
  private AreaQueryCondition() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QueryRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Range ranges = 1;
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    java.util.List<Range>
        getRangesList();
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    Range getRanges(int index);
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    int getRangesCount();
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    java.util.List<? extends RangeOrBuilder>
        getRangesOrBuilderList();
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    RangeOrBuilder getRangesOrBuilder(
        int index);

    // required .BoundingBox bbox = 2;
    /**
     * <code>required .BoundingBox bbox = 2;</code>
     */
    boolean hasBbox();
    /**
     * <code>required .BoundingBox bbox = 2;</code>
     */
    BoundingBox getBbox();
    /**
     * <code>required .BoundingBox bbox = 2;</code>
     */
    BoundingBoxOrBuilder getBboxOrBuilder();
  }
  /**
   * Protobuf type {@code QueryRequest}
   */
  public static final class QueryRequest extends
      com.google.protobuf.GeneratedMessage
      implements QueryRequestOrBuilder {
    // Use QueryRequest.newBuilder() to construct.
    private QueryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueryRequest defaultInstance;
    public static QueryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public QueryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ranges_ = new java.util.ArrayList<Range>();
                mutable_bitField0_ |= 0x00000001;
              }
              ranges_.add(input.readMessage(Range.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              BoundingBox.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = bbox_.toBuilder();
              }
              bbox_ = input.readMessage(BoundingBox.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bbox_);
                bbox_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ranges_ = java.util.Collections.unmodifiableList(ranges_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AreaQueryCondition.internal_static_QueryRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AreaQueryCondition.internal_static_QueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryRequest.class, Builder.class);
    }

    public static com.google.protobuf.Parser<QueryRequest> PARSER =
        new com.google.protobuf.AbstractParser<QueryRequest>() {
      public QueryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<QueryRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .Range ranges = 1;
    public static final int RANGES_FIELD_NUMBER = 1;
    private java.util.List<Range> ranges_;
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public java.util.List<Range> getRangesList() {
      return ranges_;
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public java.util.List<? extends RangeOrBuilder>
        getRangesOrBuilderList() {
      return ranges_;
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public int getRangesCount() {
      return ranges_.size();
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public Range getRanges(int index) {
      return ranges_.get(index);
    }
    /**
     * <code>repeated .Range ranges = 1;</code>
     */
    public RangeOrBuilder getRangesOrBuilder(
        int index) {
      return ranges_.get(index);
    }

    // required .BoundingBox bbox = 2;
    public static final int BBOX_FIELD_NUMBER = 2;
    private BoundingBox bbox_;
    /**
     * <code>required .BoundingBox bbox = 2;</code>
     */
    public boolean hasBbox() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BoundingBox bbox = 2;</code>
     */
    public BoundingBox getBbox() {
      return bbox_;
    }
    /**
     * <code>required .BoundingBox bbox = 2;</code>
     */
    public BoundingBoxOrBuilder getBboxOrBuilder() {
      return bbox_;
    }

    private void initFields() {
      ranges_ = java.util.Collections.emptyList();
      bbox_ = BoundingBox.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBbox()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRangesCount(); i++) {
        if (!getRanges(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getBbox().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ranges_.size(); i++) {
        output.writeMessage(1, ranges_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, bbox_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < ranges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ranges_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bbox_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QueryRequest)) {
        return super.equals(obj);
      }
      QueryRequest other = (QueryRequest) obj;

      boolean result = true;
      result = result && getRangesList()
          .equals(other.getRangesList());
      result = result && (hasBbox() == other.hasBbox());
      if (hasBbox()) {
        result = result && getBbox()
            .equals(other.getBbox());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getRangesCount() > 0) {
        hash = (37 * hash) + RANGES_FIELD_NUMBER;
        hash = (53 * hash) + getRangesList().hashCode();
      }
      if (hasBbox()) {
        hash = (37 * hash) + BBOX_FIELD_NUMBER;
        hash = (53 * hash) + getBbox().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QueryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QueryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QueryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QueryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QueryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AreaQueryCondition.internal_static_QueryRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AreaQueryCondition.internal_static_QueryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryRequest.class, Builder.class);
      }

      // Construct using cn.edu.whu.stdb.core.query.protobuf.AreaQueryCondition.QueryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRangesFieldBuilder();
          getBboxFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rangesBuilder_ == null) {
          ranges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rangesBuilder_.clear();
        }
        if (bboxBuilder_ == null) {
          bbox_ = BoundingBox.getDefaultInstance();
        } else {
          bboxBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AreaQueryCondition.internal_static_QueryRequest_descriptor;
      }

      public QueryRequest getDefaultInstanceForType() {
        return QueryRequest.getDefaultInstance();
      }

      public QueryRequest build() {
        QueryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QueryRequest buildPartial() {
        QueryRequest result = new QueryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rangesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            ranges_ = java.util.Collections.unmodifiableList(ranges_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ranges_ = ranges_;
        } else {
          result.ranges_ = rangesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (bboxBuilder_ == null) {
          result.bbox_ = bbox_;
        } else {
          result.bbox_ = bboxBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryRequest) {
          return mergeFrom((QueryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryRequest other) {
        if (other == QueryRequest.getDefaultInstance()) return this;
        if (rangesBuilder_ == null) {
          if (!other.ranges_.isEmpty()) {
            if (ranges_.isEmpty()) {
              ranges_ = other.ranges_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRangesIsMutable();
              ranges_.addAll(other.ranges_);
            }
            onChanged();
          }
        } else {
          if (!other.ranges_.isEmpty()) {
            if (rangesBuilder_.isEmpty()) {
              rangesBuilder_.dispose();
              rangesBuilder_ = null;
              ranges_ = other.ranges_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rangesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRangesFieldBuilder() : null;
            } else {
              rangesBuilder_.addAllMessages(other.ranges_);
            }
          }
        }
        if (other.hasBbox()) {
          mergeBbox(other.getBbox());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBbox()) {
          
          return false;
        }
        for (int i = 0; i < getRangesCount(); i++) {
          if (!getRanges(i).isInitialized()) {
            
            return false;
          }
        }
        if (!getBbox().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Range ranges = 1;
      private java.util.List<Range> ranges_ =
        java.util.Collections.emptyList();
      private void ensureRangesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ranges_ = new java.util.ArrayList<Range>(ranges_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Range, Range.Builder, RangeOrBuilder> rangesBuilder_;

      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public java.util.List<Range> getRangesList() {
        if (rangesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ranges_);
        } else {
          return rangesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public int getRangesCount() {
        if (rangesBuilder_ == null) {
          return ranges_.size();
        } else {
          return rangesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Range getRanges(int index) {
        if (rangesBuilder_ == null) {
          return ranges_.get(index);
        } else {
          return rangesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder setRanges(
          int index, Range value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.set(index, value);
          onChanged();
        } else {
          rangesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder setRanges(
          int index, Range.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.set(index, builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(Range value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.add(value);
          onChanged();
        } else {
          rangesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(
          int index, Range value) {
        if (rangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRangesIsMutable();
          ranges_.add(index, value);
          onChanged();
        } else {
          rangesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(
          Range.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.add(builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addRanges(
          int index, Range.Builder builderForValue) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.add(index, builderForValue.build());
          onChanged();
        } else {
          rangesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder addAllRanges(
          Iterable<? extends Range> values) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          super.addAll(values, ranges_);
          onChanged();
        } else {
          rangesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder clearRanges() {
        if (rangesBuilder_ == null) {
          ranges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rangesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Builder removeRanges(int index) {
        if (rangesBuilder_ == null) {
          ensureRangesIsMutable();
          ranges_.remove(index);
          onChanged();
        } else {
          rangesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Range.Builder getRangesBuilder(
          int index) {
        return getRangesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public RangeOrBuilder getRangesOrBuilder(
          int index) {
        if (rangesBuilder_ == null) {
          return ranges_.get(index);  } else {
          return rangesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public java.util.List<? extends RangeOrBuilder>
           getRangesOrBuilderList() {
        if (rangesBuilder_ != null) {
          return rangesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ranges_);
        }
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Range.Builder addRangesBuilder() {
        return getRangesFieldBuilder().addBuilder(
            Range.getDefaultInstance());
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public Range.Builder addRangesBuilder(
          int index) {
        return getRangesFieldBuilder().addBuilder(
            index, Range.getDefaultInstance());
      }
      /**
       * <code>repeated .Range ranges = 1;</code>
       */
      public java.util.List<Range.Builder>
           getRangesBuilderList() {
        return getRangesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Range, Range.Builder, RangeOrBuilder>
          getRangesFieldBuilder() {
        if (rangesBuilder_ == null) {
          rangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Range, Range.Builder, RangeOrBuilder>(
                  ranges_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          ranges_ = null;
        }
        return rangesBuilder_;
      }

      // required .BoundingBox bbox = 2;
      private BoundingBox bbox_ = BoundingBox.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          BoundingBox, BoundingBox.Builder, BoundingBoxOrBuilder> bboxBuilder_;
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public boolean hasBbox() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public BoundingBox getBbox() {
        if (bboxBuilder_ == null) {
          return bbox_;
        } else {
          return bboxBuilder_.getMessage();
        }
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public Builder setBbox(BoundingBox value) {
        if (bboxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bbox_ = value;
          onChanged();
        } else {
          bboxBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public Builder setBbox(
          BoundingBox.Builder builderForValue) {
        if (bboxBuilder_ == null) {
          bbox_ = builderForValue.build();
          onChanged();
        } else {
          bboxBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public Builder mergeBbox(BoundingBox value) {
        if (bboxBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              bbox_ != BoundingBox.getDefaultInstance()) {
            bbox_ =
              BoundingBox.newBuilder(bbox_).mergeFrom(value).buildPartial();
          } else {
            bbox_ = value;
          }
          onChanged();
        } else {
          bboxBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public Builder clearBbox() {
        if (bboxBuilder_ == null) {
          bbox_ = BoundingBox.getDefaultInstance();
          onChanged();
        } else {
          bboxBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public BoundingBox.Builder getBboxBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBboxFieldBuilder().getBuilder();
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      public BoundingBoxOrBuilder getBboxOrBuilder() {
        if (bboxBuilder_ != null) {
          return bboxBuilder_.getMessageOrBuilder();
        } else {
          return bbox_;
        }
      }
      /**
       * <code>required .BoundingBox bbox = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BoundingBox, BoundingBox.Builder, BoundingBoxOrBuilder>
          getBboxFieldBuilder() {
        if (bboxBuilder_ == null) {
          bboxBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BoundingBox, BoundingBox.Builder, BoundingBoxOrBuilder>(
                  bbox_,
                  getParentForChildren(),
                  isClean());
          bbox_ = null;
        }
        return bboxBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:QueryRequest)
    }

    static {
      defaultInstance = new QueryRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QueryRequest)
  }

  public interface QueryResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bytes result = 1;
    /**
     * <code>repeated bytes result = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getResultList();
    /**
     * <code>repeated bytes result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated bytes result = 1;</code>
     */
    com.google.protobuf.ByteString getResult(int index);
  }
  /**
   * Protobuf type {@code QueryResponse}
   */
  public static final class QueryResponse extends
      com.google.protobuf.GeneratedMessage
      implements QueryResponseOrBuilder {
    // Use QueryResponse.newBuilder() to construct.
    private QueryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueryResponse defaultInstance;
    public static QueryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public QueryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AreaQueryCondition.internal_static_QueryResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AreaQueryCondition.internal_static_QueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryResponse.class, Builder.class);
    }

    public static com.google.protobuf.Parser<QueryResponse> PARSER =
        new com.google.protobuf.AbstractParser<QueryResponse>() {
      public QueryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<QueryResponse> getParserForType() {
      return PARSER;
    }

    // repeated bytes result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> result_;
    /**
     * <code>repeated bytes result = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getResultList() {
      return result_;
    }
    /**
     * <code>repeated bytes result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated bytes result = 1;</code>
     */
    public com.google.protobuf.ByteString getResult(int index) {
      return result_.get(index);
    }

    private void initFields() {
      result_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < result_.size(); i++) {
        output.writeBytes(1, result_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < result_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(result_.get(i));
        }
        size += dataSize;
        size += 1 * getResultList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QueryResponse)) {
        return super.equals(obj);
      }
      QueryResponse other = (QueryResponse) obj;

      boolean result = true;
      result = result && getResultList()
          .equals(other.getResultList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QueryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QueryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QueryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QueryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QueryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QueryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AreaQueryCondition.internal_static_QueryResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AreaQueryCondition.internal_static_QueryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryResponse.class, Builder.class);
      }

      // Construct using cn.edu.whu.stdb.core.query.protobuf.AreaQueryCondition.QueryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AreaQueryCondition.internal_static_QueryResponse_descriptor;
      }

      public QueryResponse getDefaultInstanceForType() {
        return QueryResponse.getDefaultInstance();
      }

      public QueryResponse build() {
        QueryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QueryResponse buildPartial() {
        QueryResponse result = new QueryResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryResponse) {
          return mergeFrom((QueryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryResponse other) {
        if (other == QueryResponse.getDefaultInstance()) return this;
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes result = 1;
      private java.util.List<com.google.protobuf.ByteString> result_ = java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = new java.util.ArrayList<com.google.protobuf.ByteString>(result_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes result = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getResultList() {
        return java.util.Collections.unmodifiableList(result_);
      }
      /**
       * <code>repeated bytes result = 1;</code>
       */
      public int getResultCount() {
        return result_.size();
      }
      /**
       * <code>repeated bytes result = 1;</code>
       */
      public com.google.protobuf.ByteString getResult(int index) {
        return result_.get(index);
      }
      /**
       * <code>repeated bytes result = 1;</code>
       */
      public Builder setResult(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResultIsMutable();
        result_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes result = 1;</code>
       */
      public Builder addResult(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResultIsMutable();
        result_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes result = 1;</code>
       */
      public Builder addAllResult(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureResultIsMutable();
        super.addAll(values, result_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes result = 1;</code>
       */
      public Builder clearResult() {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:QueryResponse)
    }

    static {
      defaultInstance = new QueryResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:QueryResponse)
  }

  public interface RangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string geohash = 1;
    /**
     * <code>required string geohash = 1;</code>
     */
    boolean hasGeohash();
    /**
     * <code>required string geohash = 1;</code>
     */
    String getGeohash();
    /**
     * <code>required string geohash = 1;</code>
     */
    com.google.protobuf.ByteString
        getGeohashBytes();
  }
  /**
   * Protobuf type {@code Range}
   */
  public static final class Range extends
      com.google.protobuf.GeneratedMessage
      implements RangeOrBuilder {
    // Use Range.newBuilder() to construct.
    private Range(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Range(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Range defaultInstance;
    public static Range getDefaultInstance() {
      return defaultInstance;
    }

    public Range getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Range(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              geohash_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AreaQueryCondition.internal_static_Range_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AreaQueryCondition.internal_static_Range_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Range.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Range> PARSER =
        new com.google.protobuf.AbstractParser<Range>() {
      public Range parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Range(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Range> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string geohash = 1;
    public static final int GEOHASH_FIELD_NUMBER = 1;
    private Object geohash_;
    /**
     * <code>required string geohash = 1;</code>
     */
    public boolean hasGeohash() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string geohash = 1;</code>
     */
    public String getGeohash() {
      Object ref = geohash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          geohash_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string geohash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGeohashBytes() {
      Object ref = geohash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        geohash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      geohash_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGeohash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGeohashBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGeohashBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Range)) {
        return super.equals(obj);
      }
      Range other = (Range) obj;

      boolean result = true;
      result = result && (hasGeohash() == other.hasGeohash());
      if (hasGeohash()) {
        result = result && getGeohash()
            .equals(other.getGeohash());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasGeohash()) {
        hash = (37 * hash) + GEOHASH_FIELD_NUMBER;
        hash = (53 * hash) + getGeohash().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Range parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Range parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Range parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Range parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Range parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Range parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Range parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Range parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Range parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Range parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Range prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Range}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AreaQueryCondition.internal_static_Range_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AreaQueryCondition.internal_static_Range_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Range.class, Builder.class);
      }

      // Construct using cn.edu.whu.stdb.core.query.protobuf.AreaQueryCondition.Range.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        geohash_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AreaQueryCondition.internal_static_Range_descriptor;
      }

      public Range getDefaultInstanceForType() {
        return Range.getDefaultInstance();
      }

      public Range build() {
        Range result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Range buildPartial() {
        Range result = new Range(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.geohash_ = geohash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Range) {
          return mergeFrom((Range)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Range other) {
        if (other == Range.getDefaultInstance()) return this;
        if (other.hasGeohash()) {
          bitField0_ |= 0x00000001;
          geohash_ = other.geohash_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGeohash()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Range parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Range) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string geohash = 1;
      private Object geohash_ = "";
      /**
       * <code>required string geohash = 1;</code>
       */
      public boolean hasGeohash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string geohash = 1;</code>
       */
      public String getGeohash() {
        Object ref = geohash_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          geohash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string geohash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGeohashBytes() {
        Object ref = geohash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          geohash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string geohash = 1;</code>
       */
      public Builder setGeohash(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        geohash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string geohash = 1;</code>
       */
      public Builder clearGeohash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        geohash_ = getDefaultInstance().getGeohash();
        onChanged();
        return this;
      }
      /**
       * <code>required string geohash = 1;</code>
       */
      public Builder setGeohashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        geohash_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Range)
    }

    static {
      defaultInstance = new Range(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Range)
  }

  public interface BoundingBoxOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double minLat = 1;
    /**
     * <code>required double minLat = 1;</code>
     */
    boolean hasMinLat();
    /**
     * <code>required double minLat = 1;</code>
     */
    double getMinLat();

    // required double minLng = 2;
    /**
     * <code>required double minLng = 2;</code>
     */
    boolean hasMinLng();
    /**
     * <code>required double minLng = 2;</code>
     */
    double getMinLng();

    // required double maxLat = 3;
    /**
     * <code>required double maxLat = 3;</code>
     */
    boolean hasMaxLat();
    /**
     * <code>required double maxLat = 3;</code>
     */
    double getMaxLat();

    // required double maxLng = 4;
    /**
     * <code>required double maxLng = 4;</code>
     */
    boolean hasMaxLng();
    /**
     * <code>required double maxLng = 4;</code>
     */
    double getMaxLng();
  }
  /**
   * Protobuf type {@code BoundingBox}
   */
  public static final class BoundingBox extends
      com.google.protobuf.GeneratedMessage
      implements BoundingBoxOrBuilder {
    // Use BoundingBox.newBuilder() to construct.
    private BoundingBox(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BoundingBox(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BoundingBox defaultInstance;
    public static BoundingBox getDefaultInstance() {
      return defaultInstance;
    }

    public BoundingBox getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BoundingBox(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              minLat_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              minLng_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              maxLat_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              maxLng_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AreaQueryCondition.internal_static_BoundingBox_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AreaQueryCondition.internal_static_BoundingBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoundingBox.class, Builder.class);
    }

    public static com.google.protobuf.Parser<BoundingBox> PARSER =
        new com.google.protobuf.AbstractParser<BoundingBox>() {
      public BoundingBox parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoundingBox(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<BoundingBox> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double minLat = 1;
    public static final int MINLAT_FIELD_NUMBER = 1;
    private double minLat_;
    /**
     * <code>required double minLat = 1;</code>
     */
    public boolean hasMinLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double minLat = 1;</code>
     */
    public double getMinLat() {
      return minLat_;
    }

    // required double minLng = 2;
    public static final int MINLNG_FIELD_NUMBER = 2;
    private double minLng_;
    /**
     * <code>required double minLng = 2;</code>
     */
    public boolean hasMinLng() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double minLng = 2;</code>
     */
    public double getMinLng() {
      return minLng_;
    }

    // required double maxLat = 3;
    public static final int MAXLAT_FIELD_NUMBER = 3;
    private double maxLat_;
    /**
     * <code>required double maxLat = 3;</code>
     */
    public boolean hasMaxLat() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double maxLat = 3;</code>
     */
    public double getMaxLat() {
      return maxLat_;
    }

    // required double maxLng = 4;
    public static final int MAXLNG_FIELD_NUMBER = 4;
    private double maxLng_;
    /**
     * <code>required double maxLng = 4;</code>
     */
    public boolean hasMaxLng() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double maxLng = 4;</code>
     */
    public double getMaxLng() {
      return maxLng_;
    }

    private void initFields() {
      minLat_ = 0D;
      minLng_ = 0D;
      maxLat_ = 0D;
      maxLng_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMinLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinLng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaxLng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, minLat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, minLng_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, maxLat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, maxLng_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, minLat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, minLng_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, maxLat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, maxLng_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BoundingBox)) {
        return super.equals(obj);
      }
      BoundingBox other = (BoundingBox) obj;

      boolean result = true;
      result = result && (hasMinLat() == other.hasMinLat());
      if (hasMinLat()) {
        result = result && (Double.doubleToLongBits(getMinLat())    == Double.doubleToLongBits(other.getMinLat()));
      }
      result = result && (hasMinLng() == other.hasMinLng());
      if (hasMinLng()) {
        result = result && (Double.doubleToLongBits(getMinLng())    == Double.doubleToLongBits(other.getMinLng()));
      }
      result = result && (hasMaxLat() == other.hasMaxLat());
      if (hasMaxLat()) {
        result = result && (Double.doubleToLongBits(getMaxLat())    == Double.doubleToLongBits(other.getMaxLat()));
      }
      result = result && (hasMaxLng() == other.hasMaxLng());
      if (hasMaxLng()) {
        result = result && (Double.doubleToLongBits(getMaxLng())    == Double.doubleToLongBits(other.getMaxLng()));
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMinLat()) {
        hash = (37 * hash) + MINLAT_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getMinLat()));
      }
      if (hasMinLng()) {
        hash = (37 * hash) + MINLNG_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getMinLng()));
      }
      if (hasMaxLat()) {
        hash = (37 * hash) + MAXLAT_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getMaxLat()));
      }
      if (hasMaxLng()) {
        hash = (37 * hash) + MAXLNG_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getMaxLng()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BoundingBox parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoundingBox parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoundingBox parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoundingBox parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoundingBox parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BoundingBox parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BoundingBox parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BoundingBox parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BoundingBox parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BoundingBox parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BoundingBox prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BoundingBox}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BoundingBoxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AreaQueryCondition.internal_static_BoundingBox_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AreaQueryCondition.internal_static_BoundingBox_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BoundingBox.class, Builder.class);
      }

      // Construct using cn.edu.whu.stdb.core.query.protobuf.AreaQueryCondition.BoundingBox.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        minLat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        minLng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxLat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxLng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AreaQueryCondition.internal_static_BoundingBox_descriptor;
      }

      public BoundingBox getDefaultInstanceForType() {
        return BoundingBox.getDefaultInstance();
      }

      public BoundingBox build() {
        BoundingBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BoundingBox buildPartial() {
        BoundingBox result = new BoundingBox(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.minLat_ = minLat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.minLng_ = minLng_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxLat_ = maxLat_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxLng_ = maxLng_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BoundingBox) {
          return mergeFrom((BoundingBox)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BoundingBox other) {
        if (other == BoundingBox.getDefaultInstance()) return this;
        if (other.hasMinLat()) {
          setMinLat(other.getMinLat());
        }
        if (other.hasMinLng()) {
          setMinLng(other.getMinLng());
        }
        if (other.hasMaxLat()) {
          setMaxLat(other.getMaxLat());
        }
        if (other.hasMaxLng()) {
          setMaxLng(other.getMaxLng());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMinLat()) {
          
          return false;
        }
        if (!hasMinLng()) {
          
          return false;
        }
        if (!hasMaxLat()) {
          
          return false;
        }
        if (!hasMaxLng()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BoundingBox parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BoundingBox) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double minLat = 1;
      private double minLat_ ;
      /**
       * <code>required double minLat = 1;</code>
       */
      public boolean hasMinLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double minLat = 1;</code>
       */
      public double getMinLat() {
        return minLat_;
      }
      /**
       * <code>required double minLat = 1;</code>
       */
      public Builder setMinLat(double value) {
        bitField0_ |= 0x00000001;
        minLat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double minLat = 1;</code>
       */
      public Builder clearMinLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minLat_ = 0D;
        onChanged();
        return this;
      }

      // required double minLng = 2;
      private double minLng_ ;
      /**
       * <code>required double minLng = 2;</code>
       */
      public boolean hasMinLng() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double minLng = 2;</code>
       */
      public double getMinLng() {
        return minLng_;
      }
      /**
       * <code>required double minLng = 2;</code>
       */
      public Builder setMinLng(double value) {
        bitField0_ |= 0x00000002;
        minLng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double minLng = 2;</code>
       */
      public Builder clearMinLng() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minLng_ = 0D;
        onChanged();
        return this;
      }

      // required double maxLat = 3;
      private double maxLat_ ;
      /**
       * <code>required double maxLat = 3;</code>
       */
      public boolean hasMaxLat() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double maxLat = 3;</code>
       */
      public double getMaxLat() {
        return maxLat_;
      }
      /**
       * <code>required double maxLat = 3;</code>
       */
      public Builder setMaxLat(double value) {
        bitField0_ |= 0x00000004;
        maxLat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double maxLat = 3;</code>
       */
      public Builder clearMaxLat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxLat_ = 0D;
        onChanged();
        return this;
      }

      // required double maxLng = 4;
      private double maxLng_ ;
      /**
       * <code>required double maxLng = 4;</code>
       */
      public boolean hasMaxLng() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double maxLng = 4;</code>
       */
      public double getMaxLng() {
        return maxLng_;
      }
      /**
       * <code>required double maxLng = 4;</code>
       */
      public Builder setMaxLng(double value) {
        bitField0_ |= 0x00000008;
        maxLng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double maxLng = 4;</code>
       */
      public Builder clearMaxLng() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxLng_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BoundingBox)
    }

    static {
      defaultInstance = new BoundingBox(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BoundingBox)
  }

  /**
   * Protobuf service {@code QueryService}
   */
  public static abstract class QueryService
      implements com.google.protobuf.Service {
    protected QueryService() {}

    public interface Interface {
      /**
       * <code>rpc query(.QueryRequest) returns (.QueryResponse);</code>
       */
      public abstract void query(
          com.google.protobuf.RpcController controller,
          QueryRequest request,
          com.google.protobuf.RpcCallback<QueryResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new QueryService() {
        @Override
        public  void query(
            com.google.protobuf.RpcController controller,
            QueryRequest request,
            com.google.protobuf.RpcCallback<QueryResponse> done) {
          impl.query(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.query(controller, (QueryRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return QueryRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return QueryResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc query(.QueryRequest) returns (.QueryResponse);</code>
     */
    public abstract void query(
        com.google.protobuf.RpcController controller,
        QueryRequest request,
        com.google.protobuf.RpcCallback<QueryResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return AreaQueryCondition.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.query(controller, (QueryRequest)request,
            com.google.protobuf.RpcUtil.<QueryResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return QueryRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return QueryResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends QueryService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void query(
          com.google.protobuf.RpcController controller,
          QueryRequest request,
          com.google.protobuf.RpcCallback<QueryResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          QueryResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            QueryResponse.class,
            QueryResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public QueryResponse query(
          com.google.protobuf.RpcController controller,
          QueryRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public QueryResponse query(
          com.google.protobuf.RpcController controller,
          QueryRequest request)
          throws com.google.protobuf.ServiceException {
        return (QueryResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          QueryResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:QueryService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_QueryResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Range_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Range_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BoundingBox_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BoundingBox_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030AreaQueryCondition.proto\"B\n\014QueryReque" +
      "st\022\026\n\006ranges\030\001 \003(\0132\006.Range\022\032\n\004bbox\030\002 \002(\013" +
      "2\014.BoundingBox\"\037\n\rQueryResponse\022\016\n\006resul" +
      "t\030\001 \003(\014\"\030\n\005Range\022\017\n\007geohash\030\001 \002(\t\"M\n\013Bou" +
      "ndingBox\022\016\n\006minLat\030\001 \002(\001\022\016\n\006minLng\030\002 \002(\001" +
      "\022\016\n\006maxLat\030\003 \002(\001\022\016\n\006maxLng\030\004 \002(\00126\n\014Quer" +
      "yService\022&\n\005query\022\r.QueryRequest\032\016.Query" +
      "ResponseBA\n#cn.edu.whu.stdb.core.query.p" +
      "rotobufB\022AreaQueryConditionH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_QueryRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_QueryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_QueryRequest_descriptor,
              new String[] { "Ranges", "Bbox", });
          internal_static_QueryResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_QueryResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_QueryResponse_descriptor,
              new String[] { "Result", });
          internal_static_Range_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Range_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Range_descriptor,
              new String[] { "Geohash", });
          internal_static_BoundingBox_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_BoundingBox_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BoundingBox_descriptor,
              new String[] { "MinLat", "MinLng", "MaxLat", "MaxLng", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
